### ISSUE TITLE
Missing v1.2.3 tag

### ISSUE THREAD

**Issue by catwell** [arcapos/luaproxy#1]
Your rockspec is looking for a v1.2.3 tag, but it does not exist in the GitHub repository.

**Comment by mbalmer** [comment]
I just created a release 1.1.4, this number reflects the current library version.

**Comment by catwell** [comment]
OK, I will create a new rockspec for 1.1.4 and remove the existing rockspec for 1.2.3 in the rockspecs repository then (the version number going backwards is weird though...).
